{% set version = "0.4.3" %}

package:
  name: h5netcdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: c205774de4c9930de5fcc3d5f7854c87ad218aa9b28ef77b5c3094d2463b1da4

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - h5py
  run:
    - python
    - h5py

test:
  imports:
    - h5netcdf

about:
  home: https://github.com/shoyer/h5netcdf
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'netCDF4 via h5py.'

extra:
  recipe-maintainers:
    - jhamman
    - jjhelmus
    - ocefpaf
    - shoyer
