{% set version = "1.0.2" %}

package:
  name: h5netcdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: 8808a1e095f0122b4fb408cc98c60adf399bd57fef48d1ca7cdf4cda1d0a6b4a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - h5py
  run:
    - python >=3.6
    - h5py
    - packaging

test:
  imports:
    - h5netcdf

about:
  home: https://github.com/shoyer/h5netcdf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Pythonic interface to netCDF4 via h5py

extra:
  recipe-maintainers:
    - hmaarrfk
    - jhamman
    - ocefpaf
    - shoyer
    - kmuehlbauer
