{% set version = "0.5.0" %}

package:
  name: h5netcdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: 9c6bf9ed7e5b3d719afb041ca6193182084c9d8c2d3e1d6b2b1148f08bc729b2

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - h5py
  run:
    - python
    - h5py

test:
  imports:
    - h5netcdf

about:
  home: https://github.com/shoyer/h5netcdf
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'netCDF4 via h5py.'

extra:
  recipe-maintainers:
    - jhamman
    - jjhelmus
    - ocefpaf
    - shoyer
