{% set version = "0.3.0" %}

package:
    name: h5netcdf
    version: {{ version }}

source:
    fn: h5netcdf-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
    sha256: 630b5f5e586418654140adb6947d4f7e376828557dc720cdb413fc760b36259a

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - h5py
    run:
        - python
        - h5py

test:
    imports:
        - h5netcdf

about:
    home: https://github.com/shoyer/h5netcdf
    license: BSD 3-Clause
    summary: 'netCDF4 via h5py.'

extra:
    recipe-maintainers:
        - jhamman
        - ocefpaf
        - shoyer
