{% set version = "0.13.0" %}

package:
  name: h5netcdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: 43ecc47614ae804879b51cc95d6264520fcddfe83ccfa7d92b6e236da7dc25db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - h5py
  run:
    - python >=3
    - h5py

test:
  imports:
    - h5netcdf

about:
  home: https://github.com/shoyer/h5netcdf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Pythonic interface to netCDF4 via h5py

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
    - kmuehlbauer
