{% set version = "0.6.0" %}

package:
  name: h5netcdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: 5814872ed7738fa2d253402648dbd41810177e43c8b5c5979cf9077b7b88b5b2

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - h5py
  run:
    - python
    - h5py

test:
  imports:
    - h5netcdf

about:
  home: https://github.com/shoyer/h5netcdf
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'netCDF4 via h5py.'

extra:
  recipe-maintainers:
    - jhamman
    - jjhelmus
    - ocefpaf
    - shoyer
