{% set version = "0.7.4" %}

package:
  name: h5netcdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/h5netcdf/h5netcdf-{{ version }}.tar.gz
  sha256: 564e785296cebdc5b2ac13965d8ff454e172287bce7643521e8d9d2fd01682fd

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - h5py
  run:
    - python
    - h5py

test:
  imports:
    - h5netcdf

about:
  home: https://github.com/shoyer/h5netcdf
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Pythonic interface to netCDF4 via h5py'

extra:
  recipe-maintainers:
    - jhamman
    - jjhelmus
    - ocefpaf
    - shoyer
