travis:
  secure:
    BINSTAR_TOKEN: XR9YnPjvKzAF8J2BLsFSgI07YrJ/nXlWGj0UoHP6SaGJ3JZixgQzGDk7aNkXk1YsOkAawYx7l1Gmr4dQWcTAfklXt3f0gDQY8lWWsBAw8wEqJudtyOodHNqX1A6G3BcyG618LiDW33rmLVBzJ60npw2X4jYkVaqB6l22/RDNxqMazHFSEnOhDIkGo1UHgZhHfSEuqhONS/y5KdbSjclQTR2hSurJ3K7HcP5dT/waDz91e4x2isn7EAeulWRZ7qAC95Ox3FTFIocFqqQC+iBNly2qtGuxoSWzitscLs+MqWf0mqFt6Nt1BZ87HksDto43vg/jbFGqTZXXjtTJkMryYE7KHgoRLybpRD4qYCZnp2giS9Mm8VuY/9zafeVtfnwR3zNhpNCYOF8dHpykwnwp1tVvZkWmJpiAKyizdvYPYYlEbiwoELevTvWtC4U6q4EWomWRe7vR9KmjUZyqa/NPZsQVtHbWXiNA56hB7EfyW0n8fNpsRm/m2iPCrlT+GRIbSAFW0RcyGM9H5+h6yhSAFJayCKIYbdgXkTVGt/Ixq5wnAgMl4jJ7BKB8CCoDFoG4E1me7X41LTmXSAssO7TirBb/NGegC8N/ihuOb0FHV+jm9OwO7Bf85uNEEDjJBrG9HUKoi4GhSX3xS7tkdl+SBO0LmmcG3zIqGoKkk9DFC98=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
