travis:
  secure:
    BINSTAR_TOKEN: PptHrYae1c8CJlYa8vDN1bQZ7l1Ng0SrgOT3yqkgtZV8aNPyM2UZKL1jNAIGKqY4yu7p42CV0qC8sI3WCRDZU5zkDEehVrPhnGF4rnxQcZuZKq/zTQLNBRoooVDragAzx389wOY0NAi4aDGII0dEM3x9kcS1O7dFVJvvez8cpGNQ7D/neq98omci4mdLsghcwtF3fxz0dIrUO5QzhWOf/5xFvAo0AhsszlIo3f5aaQ24hirubiQRdsp7mgcLitWOlhFIdIj6Bb8viSs+08KYbFZNyKRE3DXo44iMPxxFQQGQWbPZpO1Y1AUsMFja0qr4/OO6SGf7CqcTy9Fm90U7ID8m8/eW/rlIKlQZjRJ6NgtzbWClfMXfuNdIPscASWqLFZdfzTDhRPjpQAligt5DnPh9a+cSQBJC6hVfd/jPf1AWPalNbUUaMR5XxLoJFFh0PusZvzXCLZoXerE1g8OBjB3Y9MINUxxj/4oz6SNuJbkUd7e9n6NTUVz+hWIAId4GAwukfK5xH7/Cxxh1+dehqTBe51tTy8OBcuj0973OpVoDaPjCx33Dd5vxgCqxsctY/Tph4u68xuS8h5wXO1V5vF1+A5NYBVrfrIcMv1W4VzP098J5SSU7iDWTZcsQ9Vp6CuIQSP4rgmslA2cWc3nQwdsp3tvXvkvwWpm/zhFxrhM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
