travis:
  secure:
    BINSTAR_TOKEN: rduYj9smO69Y9aLQtoWBKbNXHUsox2Ak+zuKcxqGSYYd6cNMnMgLgdC90UnFL3lgh+PXQ3NIqSZS3dWHG5MLOyJ+QlUwBRTMfu6gf+nECCJgTRewFV9ca7qABi9Ojz1qtGq7jmanocAmJsEmfcC7vKV8sKJIzChr//4dPqbk61WTnDNPMLyyqJZ6LOMtYdRZ8LLsG9+S6oITT87g/kSH3AczkQoxEy+Vks8/E+bGVtV7X1MrZG4oTIAAJW4QvDw0r3tP/EZYbtF6vR6FOeYEcDGqviD5dyhBDdLUR4tidGrjPpPNn5Cxtuh0ztmvMow+re6LFlcfFaERPlDSJjDt0S0QhrDaqf4COzYMpVH/GRliShnUSqoK654WEALcDUGvVdXa7GwqTkeYxNQ7YN6CMo6IH2kUA1VMxCpc05T3uSjZtR9jSpUFT5E8X8YHqy7OIBAVIFzBlYhUZIKdzjC5UYo5iXDxv9704GPsIXdIhFK04O1DLztESwKjGUmpwbaX7EFJpWIl9dgjAQe5n6P/Co7Fm2mwip1YBW4TG0PN24Pjg+Vh8j1m9rLfRKkDaBIjxZJSOUB4hOrKPx3ApY7x6C+pg9SlF/a4JiW7d+cKNB8kcnlHvPwfBbuCt/xfNMQejXXCalwAcCfSEhwOJxaBRvzQA+AnA9urn8Zgq1yS3mU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
